### ISSUE TITLE
Video not full screen

### ISSUE THREAD

**Issue by hoangphan92** [skyway/skyway-ios-sdk#18]
When I make auto layout localView:SKWVideo in top:0,right:0,left:0. But when addVideoRenderer localView it's wrong. Please help me !
![img_1218](https://user-images.githubusercontent.com/25924647/43135574-1108c884-8f70-11e8-8189-14582a77f0f4.PNG)

**Comment by y-i** [comment]
This bug is now fixed.
Please try updating the SDK to v1.2.0.
