### ISSUE TITLE
[SKWConnectOption] metadata property is null when connect with other peer?

### ISSUE THREAD

**Issue by tienphong923** [skyway/skyway-ios-sdk#2]
On SkyWaySDK offical release 1.0.0, when I was tried to connect with other peer (I was set value for metadata property on SKWConnectOption) but on my partner side, metadata's value on incoming SKWDataConnection is always null. I also set value for label property (SKWConnectOption), it's working normal.

Anyone help me, please!
Thanks in advance!

**Comment by tsu-takahashi** [comment]
Thank you for the report.
We received similar reports from other developers.
We are confirming the details now. Please wait a little while and we'll get back to you as soon as possible.

**Comment by tsu-takahashi** [comment]
This bug is now fixed. 
Please try updating the SDK to v1.0.1. 
We're sorry for the inconvenience.

**Comment by tienphong923** [comment]
Wow, great work!
Thanks so much!
