### ISSUE TITLE
AirplayとSkyWayが同時に接続されない。

### ISSUE THREAD

**Issue by daisukenagata** [skyway/skyway-ios-sdk#52]
# Description of the problem

https://github.com/daisukenagata/iOS_SkyWay/issues/1

 # Environment

 - SDK version (ex. SDK v3.0.1,etc)
- Device (ex. All , etc)
- OS (ex. iOS 14 etc)
- Network (WiFi, LTE)

 # Steps to reproduce the problem

issueリンク先のサンプルアプリを動かすと、確認できます。
ReadMeに記載の各Keyは、個別にご連絡差し上げます。
https://github.com/daisukenagata/iOS_SkyWay 

こちらが連絡先です。
Mail　dbank0208@gmail.com

ご連絡、お待ちしております。

よろしくお願い致します。

**Comment by y-i** [comment]
サンプルアプリケーションのバグ以外については[こちら](https://support.skyway.io/hc/ja/community/topics)のコミュニティフォーラムをご利用ください。
