### ISSUE TITLE
How to implement share screen?

### ISSUE THREAD

**Issue by huybuidac** [skyway/skyway-ios-sdk#56]
# Description of the problem
How to implement share screen feature?

If Skyway doesn't support this feature, the sdk should have function to customize stream.

**Comment by d-matsui** [comment]
Thank you for your feedback.
Unfortunately, SkyWay doesn't support the screen sharing feature now.
We will consider to support the feature.

**Comment by huybuidac** [comment]
Thank for your reply.

I look forward to the screen sharing feature.

**Comment by huybuidac** [comment]
@d-matsui how's it going?
Is there any way to customize video stream?

**Comment by d-matsui** [comment]
Thank you for your patience and understanding.
We understand the need to support the screen sharing feature.
We are sorry, but we have decided not to develop it at this point because we are currently trying to develop other high priority things.

**Comment by huybuidac** [comment]
thanks :(
