### ISSUE TITLE
Doesn't run on iOS Simulator (Apple Silicon Mac)

### ISSUE THREAD

**Issue by HiroshiHorie** [skyway/skyway-ios-sdk#65]
# Description of the problem

The samples don't run on iOS Simulators when using Apple Silicon Macs. But running on the device works. Probably due to architecture. Please support Apple Silicon Macs or let me know if there is a workaround.

Regards

 # Environment

 - SDK version (ex. SDK v1.0.1,etc)
Latest

- Device (ex. iPhone XR, etc)
iOS Simulator

- OS (ex. iOS 12 etc)
- Network (Cable/DSL/Fiber + WiFi, MiFi, LTE, etc)

**Comment by ibuibu** [comment]
Thank you for pointing this out.

We are aware that the number of Simulator use cases is not large at this stage, as the iOS Simulator cannot acquire camera images.

Therefore, we plan to take time to implement countermeasures at this stage.

If you don't mind, could you please tell us about your use case?

We would like to use this information as a reference for considering the priority of response in this matter.

**Comment by HiroshiHorie** [comment]
Thanks for putting effort in resolving this issue.

Yes, even though the iOS Simulator cannot acquire camera images, it is quite normal for an app to be
debuggable with the Simulator. For example, if we are making an SNS app, we can not debug other features
of the app since your library will refuse to compile (for the Simulator).

And by the way, if I'm correct, iPhone and Apple Silicon should have similar architecture so 
it shouldn't be too complicated to support. (Dependency issues?)

Regards
Hiroshi

**Comment by ibuibu** [comment]
Thanks for the reply.

Yes, as you said, I think it is a problem that SkyWay is embedded so that you can't debug other functions.

We will consider the priority of this issue again in the team.

Regards.
