### ISSUE TITLE
Porting to SwiftUI

### ISSUE THREAD

**Issue by ozk-dev** [skyway/skyway-ios-sdk#67]
This is my first time contacting you.

I am working on creating a text chat and video call as my own application.
I have downloaded the sample source code and am in the process of checking it out.
My goal is to port it to SwiftUI and include an outgoing and incoming call screen with Callkit, but I can't get it to work. The code I have changed is as follows, but I was wondering if you could advise me on the process

 # Explanation of the problem

`peer.on(SKWPeerEventEnum.PEER_EVENT_CALL, callback: { (obj) -> Void in`
`	if let connection = obj as? SKWMediaConnection{`
`　　　　  In this part`
`　　　　  *let update = CXCallUpdate()`
`                *provider.reportNewIncomingCall(with: uuid, update: update) { error in`
`                *}`
`              self.setupMediaConnectionCallbacks(mediaConnection: connection)`
`		self.mediaConnection = `connection`
`		`connection.answer(self.localStream)`
`	}`
`})`

I've added the program for the "*" part, but the display of the following Stream does not switch, and the connection seems to be working, but the image is not displayed anymore.

 # Environment
- Device Iphone XR
- OS iOS 10 or higher
- Network (WiFi /LET)

**Comment by ibuibu** [comment]
Thank you for question.

We do not accept technical questions about using SkyWay SDK.

If you have technical questions about SkyWay, please post them in the following community.

https://support.skyway.io/hc/ja/community/topics
