### ISSUE TITLE
examplesのコードについて

### ISSUE THREAD

**Issue by jihyeon-kim** [skyway/skyway-ios-sdk#7]
swiftのexampleコードを試したのですが、
「media connection」ボタンを押す -> 戻る -> また「media connection」ボタンを押す
の動線で2回目の「media connection」が画面が固まってしまうことがあります。
ご確認宜しくお願いします。

**Comment by rokihiro** [comment]
ご報告ありがとうございます。
exampleと言うより、getUserMediaを複数回行うと取得が遅くなる不具合がありそうです。
修正には少しお時間頂きますが、確認いたします

**Comment by rokihiro** [comment]
現時点の最新版v1.2.1であれば動作が解消しております。
再度発生するようでしたら、再openをお願いいたします。
