### ISSUE TITLE
add SKWMediaStream in AVPictureInPictureController 

### ISSUE THREAD

**Issue by razermanba** [skyway/skyway-ios-sdk#76]
hi team skyway.
I'm having a problem, I need to convert SKWMediaStream video add PIP, can you give me the solution here?

**Comment by ibuibu** [comment]
Sorry to make you wait.

Sorry, technical support for the previous version of Skyway is chargeable. However, the Enterprise Edition is no longer accepted and cannot be contracted at present.

The new version of SkyWay, so please consider signing up for this contract.
https://skyway.ntt.com/

But, as the result of research, it is difficult to implement PIP in each version.
